### ISSUE TITLE
Recognize ast.arg in Variables.variables

### ISSUE THREAD

**Issue by dakoop** [kavigupta/ast_scope#2]
Thanks for this work. It looks like `ast.arg`s are being stored in `Variables.variables` so the `all_symbols` property needs to distinguish between `ast.arg` and `ast.Name` here:

https://github.com/kavigupta/ast_scope/blob/3351f043515f07d58ac7c57a71d153d50178a132/ast_scope/scope.py#L14

To reproduce (python 3.8)
```
import ast
import ast_scope
tree = ast.parse("def f(x): return y")
scope_info = ast_scope.annotate(tree)
scope_info.global_scope.children[0].symbols_in_frame
```

which should produce `AttributeError: 'arg' object has no attribute 'id'`

**Comment by kavigupta** [comment]
Sorry for the extreme delay in response. But this has been resolved sometime in the meantime.
